path_base: "/Users/Timon/Library/CloudStorage/OneDrive-Charité-UniversitätsmedizinBerlin/Shared Documents - ICN Data World/General/Data/UCSF_OLARU"
figures: "figures_ucsf"
performances: "out_per"
features: "features"